# Generated by Django 4.1.3 on 2022-11-28 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Preset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=200)),
                ("json_file", models.FileField(upload_to="")),
                ("image_file", models.FileField(upload_to="")),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
    ]
