# Generated by Django 4.1.3 on 2022-11-28 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presets", "0002_preset_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preset",
            name="image_file",
            field=models.ImageField(upload_to="image_files"),
        ),
        migrations.AlterField(
            model_name="preset",
            name="json_file",
            field=models.FileField(upload_to="json_files"),
        ),
    ]
