# Generated by Django 4.1.3 on 2022-12-02 10:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presets", "0004_preset_like_preset_save_alter_preset_image_file_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preset",
            name="like",
        ),
        migrations.RemoveField(
            model_name="preset",
            name="save",
        ),
        migrations.AlterField(
            model_name="preset",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 2, 5, 5, 40, 936020),
                verbose_name="date published",
            ),
        ),
    ]
