# Generated by Django 4.1.3 on 2022-12-05 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presets", "0006_alter_preset_pub_date_presetsave_presetlike"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preset",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 5, 0, 39, 58, 143263),
                verbose_name="date published",
            ),
        ),
    ]
