# Generated by Django 4.1.3 on 2022-12-07 02:42

import datetime
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('presets', '0007_alter_preset_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presetsave',
            name='preset',
        ),
        migrations.RemoveField(
            model_name='presetsave',
            name='user',
        ),
        migrations.AddField(
            model_name='preset',
            name='likes',
            field=models.ManyToManyField(related_name='preset_likes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='preset',
            name='saves',
            field=models.ManyToManyField(related_name='preset_saves', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preset',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 6, 21, 42, 23, 442183), verbose_name='date published'),
        ),
        migrations.DeleteModel(
            name='PresetLike',
        ),
        migrations.DeleteModel(
            name='PresetSave',
        ),
    ]
