# Generated by Django 4.1.3 on 2022-12-23 06:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presets", "0009_rename_image_file_preset_thumbnail_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preset",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 23, 1, 43, 54, 141947),
                verbose_name="date published",
            ),
        ),
        migrations.AlterField(
            model_name="preset",
            name="zip_file",
            field=models.FileField(null=True, upload_to="zip_files"),
        ),
    ]
