# Generated by Django 4.1.3 on 2022-12-23 06:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presets", "0010_alter_preset_pub_date_alter_preset_zip_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preset",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 23, 1, 44, 41, 584396),
                verbose_name="date published",
            ),
        ),
        migrations.AlterField(
            model_name="preset",
            name="zip_file",
            field=models.FileField(upload_to="zip_files", null=True, blank=True),
        ),
    ]
