# Generated by Django 4.1.3 on 2022-12-26 09:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presets", "0011_alter_preset_pub_date_alter_preset_zip_file"),
    ]

    operations = [
        migrations.RenameField(
            model_name="preset",
            old_name="count",
            new_name="like_count",
        ),
        migrations.AddField(
            model_name="preset",
            name="download_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="preset",
            name="save_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="preset",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 26, 4, 43, 44, 521373),
                verbose_name="date published",
            ),
        ),
    ]
