# Generated by Django 4.1.3 on 2022-12-31 22:19

import datetime
from django.db import migrations, models
import presets.validators.validators


class Migration(migrations.Migration):

    dependencies = [
        (
            "presets",
            "0012_rename_count_preset_like_count_preset_download_count_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="preset",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 12, 31, 17, 19, 50, 18554),
                verbose_name="date published",
            ),
        ),
        migrations.AlterField(
            model_name="preset",
            name="zip_file",
            field=models.FileField(
                upload_to="zip_files",
                validators=[presets.validators.validators.valid_preset_size],
                null=True,
                blank=True
            ),
        ),
    ]
