# Generated by Django 4.1.3 on 2023-01-02 20:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presets", "0014_alter_preset_pub_date_alter_preset_zip_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preset",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 2, 15, 11, 28, 859691),
                verbose_name="date published",
            ),
        ),
    ]
