# Generated by Django 4.1.3 on 2023-01-02 20:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presets", "0016_preset_character_alter_preset_pub_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preset",
            name="character",
            field=models.CharField(
                choices=[("M", "Maya"), ("S", "Shey"), ("O", "Other")],
                default="M",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="preset",
            name="pub_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 1, 2, 15, 30, 26, 999431),
                verbose_name="date published",
            ),
        ),
    ]
