# Generated by Django 4.1.3 on 2023-01-10 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presets", "0022_alter_preset_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preset",
            name="description",
            field=models.CharField(max_length=820),
        ),
    ]
