# Generated by Django 4.1.3 on 2023-01-10 19:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("presets", "0023_alter_preset_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="preset",
            name="user_who_submitted",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
