# Generated by Django 4.1.3 on 2023-01-11 20:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("presets", "0025_alter_preset_thumbnail_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="preset",
            name="pub_date",
        ),
        migrations.AddField(
            model_name="preset",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddField(
            model_name="preset",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
