# Generated by Django 4.1.3 on 2023-01-11 20:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("presets", "0026_remove_preset_pub_date_preset_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preset",
            name="user_who_submitted",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
