# Generated by Django 4.1.3 on 2023-01-13 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presets", "0027_alter_preset_user_who_submitted"),
    ]

    operations = [
        migrations.AddField(
            model_name="preset",
            name="view_count",
            field=models.IntegerField(default=0),
        ),
    ]
