# Generated by Django 4.1.3 on 2023-01-29 00:33

from django.db import migrations, models
import presets.validators.validators


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0030_alter_preset_created_at_alter_preset_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='zip_file',
            field=models.FileField(blank=True, null=True, upload_to='zip_files', validators=[presets.validators.validators.valid_preset_size, presets.validators.validators.valid_zip]),
        ),
    ]
