# Generated by Django 4.1.3 on 2023-01-29 01:00

from django.db import migrations, models
import presets.validators.validators


class Migration(migrations.Migration):

    dependencies = [
        ('presets', '0032_alter_preset_zip_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preset',
            name='zip_file',
            field=models.FileField(default='zip_files/preset.zip', upload_to='zip_files', validators=[presets.validators.validators.valid_preset_size, presets.validators.validators.valid_zip]),
        ),
    ]
