# Generated by Django 4.1.3 on 2023-03-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presets", "0034_alter_preset_thumbnail_file_alter_preset_zip_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preset",
            name="character",
            field=models.CharField(
                choices=[("A", "All"), ("M", "Maya"), ("S", "Shey"), ("O", "Other")],
                default="A",
                max_length=2,
            ),
        ),
    ]
