# Generated by Django 4.1.3 on 2023-03-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presets", "0035_alter_preset_character"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preset",
            name="character",
            field=models.CharField(
                choices=[
                    ("ALL", "All"),
                    ("AOI", "Aoi"),
                    ("BOL", "Bol"),
                    ("BORCO", "Borco"),
                    ("CHAKK", "Chakkar"),
                    ("CORMA", "Corman"),
                    ("EMMA", "Emma"),
                    ("ILJAH", "Iljah"),
                    ("INDRA", "Indra"),
                    ("JADEE", "Jadeen"),
                    ("JENNY", "Jenny"),
                    ("KIM", "Kim"),
                    ("KRAL", "Kral"),
                    ("LALA", "Lala"),
                    ("LEAH", "Leah"),
                    ("LEE", "Lee"),
                    ("LYNDO", "Lyndon"),
                    ("MAX", "Max"),
                    ("MAYA", "Maya"),
                    ("MERCE", "Mercer"),
                    ("MILAN", "Milanna"),
                    ("MINOT", "Minotaur"),
                    ("MORRI", "Morris"),
                    ("NERO_", "Nero Nero"),
                    ("RAWN", "Rawn"),
                    ("SEREN", "Serenia"),
                    ("SHANN", "Shannon"),
                    ("SHEY", "Shey"),
                    ("SHEYF", "Sheyfuta"),
                    ("SHIVA", "Shiva"),
                    ("SONIA", "Sonia"),
                    ("TANYA", "Tanya"),
                    ("TRIBA", "Tribalmalea1"),
                    ("ZIAD", "Ziad"),
                    ("OTHER", "Other"),
                ],
                default="ALL",
                max_length=5,
            ),
        ),
    ]
