# Generated by Django 4.1.3 on 2023-03-04 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("presets", "0036_alter_preset_character"),
    ]

    operations = [
        migrations.AlterField(
            model_name="preset",
            name="character",
            field=models.CharField(
                choices=[
                    ("ALL", "All"),
                    ("AOI", "Aoi"),
                    ("BOL", "Bol"),
                    ("BORCO", "Borco"),
                    ("CHAKKAR", "Chakkar"),
                    ("CORMAN", "Corman"),
                    ("EMMA", "Emma"),
                    ("ILJAH", "Iljah"),
                    ("INDRA", "Indra"),
                    ("JADEEN", "Jadeen"),
                    ("JENNY", "Jenny"),
                    ("KIM", "Kim"),
                    ("KRAL", "Kral"),
                    ("LALA", "Lala"),
                    ("LEAH", "Leah"),
                    ("LEE", "Lee"),
                    ("LYNDON", "Lyndon"),
                    ("MAX", "Max"),
                    ("MAYA", "Maya"),
                    ("MERCER", "Mercer"),
                    ("MILANNA", "Milanna"),
                    ("MINOTAUR", "Minotaur"),
                    ("MORRIS", "Morris"),
                    ("NERO_NERO", "Nero Nero"),
                    ("RAWN", "Rawn"),
                    ("SERENIA", "Serenia"),
                    ("SHANNON", "Shannon"),
                    ("SHEY", "Shey"),
                    ("SHEYFUTA", "Sheyfuta"),
                    ("SHIVA", "Shiva"),
                    ("SONIA", "Sonia"),
                    ("TANYA", "Tanya"),
                    ("TRIBALMALEA1", "Tribalmalea1"),
                    ("ZIAD", "Ziad"),
                    ("OTHER", "Other"),
                ],
                default="ALL",
                max_length=12,
            ),
        ),
    ]
