# Generated by Django 4.1.3 on 2023-03-15 17:47

from django.db import migrations, models
import presets.validators.validators


class Migration(migrations.Migration):

    dependencies = [
        ("presets", "0037_alter_preset_character"),
    ]

    operations = [
        migrations.CreateModel(
            name="PresetThumbnails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thumbnail_files",
                    models.ImageField(
                        default="images/default.jpg",
                        upload_to="images",
                        validators=[presets.validators.validators.valid_image_size],
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="preset",
            name="thumbnail_files",
            field=models.ManyToManyField(to="presets.presetthumbnails"),
        ),
    ]
