# Generated by Django 4.1.3 on 2023-03-17 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("presets", "0038_presetthumbnails_preset_thumbnail_files"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PresetThumbnails",
            new_name="PresetImage",
        ),
        migrations.RenameField(
            model_name="preset",
            old_name="thumbnail_files",
            new_name="images",
        ),
        migrations.RenameField(
            model_name="presetimage",
            old_name="thumbnail_files",
            new_name="image",
        ),
    ]
