# Generated by Django 4.1.3 on 2023-03-17 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("presets", "0039_rename_presetthumbnails_presetimage_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="preset",
            old_name="images",
            new_name="additional_thumbnail_files",
        ),
    ]
