# Generated by Django 4.1.3 on 2023-03-18 00:24

from django.db import migrations, models
import presets.validators.validators


class Migration(migrations.Migration):

    dependencies = [
        ("presets", "0040_rename_images_preset_additional_thumbnail_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presetimage",
            name="image",
            field=models.ImageField(
                upload_to="images",
                validators=[presets.validators.validators.valid_image_size],
            ),
        ),
    ]
